{
 "title": "Oracle RAC 性能视图",
 "tags": [
  "onekeeper",
  "template"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "hzmc-onekeeper-datasource" },
   { "name": "group", "label": "组", "query": "*" },
   { "name": "node1", "label": "节点 1", "query": "$group.*" },
   { "name": "node2", "label": "节点 2", "query": "$group.*" }
  ]
 },
 "panels": [
  {
   "title": "监听",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Listener" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Status of listener" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "实例",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Instance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Status of instance" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "逻辑读时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Logical reads response  time" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "逻辑读次数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Logical reads per second" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "5分钟错误",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Instance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Number of alerts (5min)" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "24小时错误",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Instance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Number of alerts (24h)" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "5分钟变更",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Change" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Total changes (5min)" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "24 小时变更",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Change" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Total changes (24h)" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "备份",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Instance" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "max",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "max(1m)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Status of daliy backup" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "监听",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Listener" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Status of listener" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "实例",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Instance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Status of instance" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "逻辑读时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Logical reads response  time" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "逻辑读次数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Logical reads per second" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "5分钟错误",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Instance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Number of alerts (5min)" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "24小时错误",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Instance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Number of alerts (24h)" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "5分钟变更",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Change" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Total changes (5min)" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "24 小时变更",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Change" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Total changes (24h)" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "表空间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Instance" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "max",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "max(1m)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Space stats of all tablespaces" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "表空间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Instance" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "max",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "max(1m)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Total space of all tablespaces" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "数据库登录",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "application": { "filter": "Connection" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Average connection time" ],
       "text": "setAlias(Average connection time)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Average connection time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Connection" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "sum",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "sum(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Connections per second" ],
       "text": "setAlias(Connections per second)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Connections per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "grafana-flow-panel",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 6 },
   "targets": [
    {
     "application": { "filter": "SQL Parse" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "sum",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "sum(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Latch gets per second" ],
       "text": "setAlias(Latch gets per second)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Latch gets per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQL Parse" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Latch gets time" ],
       "text": "setAlias(Latch gets time)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Latch gets time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SQL 解析",
   "type": "grafana-progress-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "application": { "filter": "Shared Pool" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Shared pool hit ratio" ],
       "text": "setAlias(Shared pool hit ratio)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Shared pool hit ratio" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Shared Pool" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Shared pool size" ],
       "text": "setAlias(Shared pool size)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Shared pool size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Shared Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Library cache size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Shared Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Row cache size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Shared Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Shared pool free size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Shared Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Library cache size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Shared Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Row cache size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Shared Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Shared pool free size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "grafana-flow-panel",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 6 },
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "sum",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "sum(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Logical reads per second" ],
       "text": "setAlias(Logical reads per second)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Logical reads per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Logical reads response  time" ],
       "text": "setAlias(Logical reads response  time)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Logical reads response  time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SQL 执行",
   "type": "grafana-progress-panel",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 6 },
   "targets": [
    {
     "application": { "filter": "Buffer Cache" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Buffer cache hit ratio" ],
       "text": "setAlias(Buffer cache hit ratio)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Buffer cache hit ratio" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Buffer Cache" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Buffer cache size" ],
       "text": "setAlias(Buffer cache size)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Buffer cache size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Buffer Cache" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Default pool size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Buffer Cache" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Keep pool size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Buffer Cache" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Recycle pool size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Buffer Cache" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Default pool size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Buffer Cache" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Keep pool size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Buffer Cache" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Recycle pool size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "grafana-flow-panel",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 6 },
   "targets": [
    {
     "application": { "filter": "SQL Commit" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "sum",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "sum(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "SQL*Net throughput" ],
       "text": "setAlias(SQL*Net throughput)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "SQL*Net throughput" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQL Commit" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "sum",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "sum(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Redo size per second" ],
       "text": "setAlias(Redo size per second)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Redo size per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SQL 提交",
   "type": "grafana-progress-panel",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "application": { "filter": "SQL Commit" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "min",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "min(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Log buffer space waits" ],
       "text": "setAlias(Log buffer space waits)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Log buffer space waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQL Commit" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Active logs" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQL Commit" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node1" },
     "item": { "filter": "Inactive logs" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQL Commit" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Active logs" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQL Commit" },
     "group": { "filter": "$group" },
     "host": { "filter": "$node2" },
     "item": { "filter": "Inactive logs" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "数据库会话",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Connection" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Total Session" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Connection" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Active session" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Connection" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "max",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "max(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Active session limit" ],
       "text": "setAlias(Active session limit)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Active session limit" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "grafana-flow-panel",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 11 },
   "targets": [
    {
     "application": { "filter": "SQL Parse" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "sum",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "sum(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total parse per second" ],
       "text": "setAlias(Total parse per second)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Total parse per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQL Parse" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Average parse time" ],
       "text": "setAlias(Average parse time)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Average parse time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "application": { "filter": "SQL Parse" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Average parse time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "grafana-flow-panel",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 11 },
   "targets": [
    {
     "application": { "filter": "SQL Execution" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "sum",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "sum(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Executions per second" ],
       "text": "setAlias(Executions per second)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Executions per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQL Execution" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Average execution time" ],
       "text": "setAlias(Average execution time)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Average execution time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "application": { "filter": "SQL Execution" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Average execution time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "grafana-flow-panel",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 11 },
   "targets": [
    {
     "application": { "filter": "SQL Commit" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "sum",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "sum(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Commits per second" ],
       "text": "setAlias(Commits per second)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Commits per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQL Commit" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Average commit time" ],
       "text": "setAlias(Average commit time)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Average commit time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "application": { "filter": "SQL Commit" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Average commit time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "application": { "filter": "Resource" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*) used in %/",
        "$1"
       ],
       "text": "replaceAlias(/(.*) used in %/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "/(.*) %/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "application": { "filter": "Cluster" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "GC buffer busy time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Cluster" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "GC buffer busy waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Cluster" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "GC cr block 2-way time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Cluster" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "GC cr block 2-way waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Cluster" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "GC cr block busy time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Cluster" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "GC cr block busy waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Cluster" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "GC current block 2-way time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Cluster" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "GC current block 2-way waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Cluster" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "GC current block busy time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Cluster" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "GC current block busy waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Mutex / Latch",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Latch: shared pool time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Latch: shared pool waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": {
      "filter": "Latch: cache buffers chains time"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": {
      "filter": "Latch: cache buffers chains waits"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Latch: row cache objects time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Latch: row cache objects waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Cursor: mutex S time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Cursor: mutex S waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Cursor: pin S wait on X time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Cursor: pin S wait on X waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Library cache: mutex X time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Latch" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Library cache: mutex X waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lock",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "application": { "filter": "Lock" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Enq: TM - contention time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Lock" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": { "filter": "Enq: TM - contention waits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Lock" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": {
      "filter": "Enq: TX - index contention time"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Lock" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": {
      "filter": "Enq: TX - index contention waits"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Lock" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": {
      "filter": "Enq: TX - row lock contention time"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Lock" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "item": {
      "filter": "Enq: TX - row lock contention waits"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "告警信息",
   "type": "hzmc-onekeeper-triggers-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": {
    "$datasource": {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "/$node1|$node2/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  }
 ]
}