{
 "title": "WebLogic 应用性能视图",
 "tags": [
  "onekeeper",
  "template"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "hzmc-onekeeper-datasource" },
   { "name": "group", "label": "组", "query": "*" },
   { "name": "host", "label": "主机", "query": "$group.*" },
   { "name": "application", "label": "JDBC", "query": "$group.$host.*" }
  ]
 },
 "panels": [
  { "title": "JVM 运行状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "运行状态",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "JVM Runtime" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "count",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "2m" ],
       "text": "count(2m)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "JVM CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Process CPU usage in %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "堆内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "JVM Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Heap Memory used in %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "堆内存使用量",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "JVM Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Heap memory used" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "垃圾回收次数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "JVM GC" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "sum",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "sum(1m)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/Number of collections per second by .*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "线程数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "JVM Thread" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Thread count" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "运行状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "吞吐量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "WLS Thread Pool" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "real" ],
       "text": "setAlias(real)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Throughput" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS Thread Pool" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         0.2
        ],
        "name": "exponentialMovingAverage",
        "params": [
         {
          "name": "smoothing",
          "options": [
           6,
           10,
           60,
           100,
           600
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "10" ],
       "text": "exponentialMovingAverage(10)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "exp" ],
       "text": "setAlias(exp)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Throughput" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "线程池",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "WLS Thread Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Active execute threads" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS Thread Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Standby threads" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "JTA",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "WLS JTA" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Committed transactions" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS JTA" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Rolled back transactions" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS JTA" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Abandoned transactions" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS JTA" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Heuristic transactions" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "活动事务",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "WLS JTA" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Active transactions" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "运行状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "请求队列",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "WLS Thread Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Pending user requests" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "活动线程",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "WLS Thread Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Idle execute threads" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS Thread Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Hogging threads" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS Thread Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Stuck threads" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS Thread Pool" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Active execute threads" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "回滚事务",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "WLS JTA" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Transactions rolled back for application errors"
     },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS JTA" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Transactions rolled back for resource errors"
     },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS JTA" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Transactions rolled back for system errors"
     },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS JTA" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Transactions rolled back for timeout"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "JMS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "WLS JMS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Connections current count" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "WLS JMS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "JMS servers current count" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "$application 运行状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "application" },
  {
   "title": "连接池",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "$application" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "active" ],
       "text": "setAlias(active)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* active connections$/" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "$application" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "available" ],
       "text": "setAlias(available)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* available connections$/" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "$application" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "unavailable " ],
       "text": "setAlias(unavailable )"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* unavailable connections$/" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "新建连接数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "$application" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* created connections$/" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "连接延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "$application" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* connection delay time$/" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "失败重连数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "$application" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* failures to reconnect/" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "数据库请求",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "$application" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*\\\" reserve requests$/"
     },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "$application" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*\\\" failed reserve requests$/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "请求等待数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "$application" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.* requests waiting for connection$/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "告警信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "告警信息",
   "type": "hzmc-onekeeper-triggers-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": {
    "$datasource": {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  }
 ]
}